### ISSUE TITLE
Ruby Doc link update

### ISSUE THREAD

**Issue by Maheshkumar-novice** [lifeparticle/Ruby-Cheatsheet#14]
Most of the links pointing to `ruby-doc` are pointing the version `2.6.x`. Do we need to update those links to point the current version? Or any automation stuff to do that (like creating some variable and update the `md` to get the value from that variable using github actions or something)?

**Comment by Maheshkumar-novice** [comment]
@lifeparticle

**Comment by lifeparticle** [comment]
Hello @[Maheshkumar-novice](https://github.com/Maheshkumar-novice)

Thank you for pointing out the issue. Yes, some kind of automation using GitHub Actions would be great!

**Comment by Maheshkumar-novice** [comment]
Great. I don't have any experience with github actions. But I'll look for any solutions. Do you have any ideas in mind?

**Comment by lifeparticle** [comment]
https://www.brianchildress.co/variables-in-markdown/

**Comment by Maheshkumar-novice** [comment]
Nice. Will look into it.

**Comment by Maheshkumar-novice** [comment]
![Screenshot](https://user-images.githubusercontent.com/67100964/178741841-a0367e15-6c37-4c3d-898a-de47e6e5464e.png)

It creates a link. But we need something that stores a value. I think we need to find another way.

I've an idea but I'm not sure it is effective or not. The idea is,
* Create all the links as variables between the comment you've done currently for news
* Select all the content between those comment
* Replace whatever content comes after `core/` in the url and replace it with the current ruby version using github action

Example,
```
<!-- doc_links starts>
[1]: link1
[2]: link2
....
<!-- doc_links ends>
```
PS: we will use [1], [2] in the md file wherever those links belong.

Replace [1], [2] links with latest ruby version using github actions. 

Let me know your suggestions and comments about this and other ideas to implement this.

**Comment by Maheshkumar-novice** [comment]
@lifeparticle

**Comment by lifeparticle** [comment]
Great work @Maheshkumar-novice. The steps you've mentioned sound good.

We can store the Ruby version inside a text file. For the GitHub Actions, we can do a network call to get the latest version of Ruby and we could compare it with the text file, and if both versions do not match we could update the links. What do you think?

**Comment by Maheshkumar-novice** [comment]
@lifeparticle Yeah. That's a great idea. I'll start working on it and try to finish it by this weekend.

**Comment by Maheshkumar-novice** [comment]
@lifeparticle PR raised. Let me know what you think about it.

**Comment by lifeparticle** [comment]
@Maheshkumar-novice sorry for the late response. I've reviewed and made some changes, let me know what you think. Thanks!

**Comment by Maheshkumar-novice** [comment]
@lifeparticle No problem. Thanks for taking time to review. Looks good to me. I've some doubts so I commented in the code. Let me know what you think.

**Comment by lifeparticle** [comment]
No problem. Sure, can't see the comments. Could you give me a link, thanks!

**Comment by Maheshkumar-novice** [comment]
It's strange. Comments and Suggestions are visible in PR to me. Can you share the screenshot please? So that I can proceed with my checks.

**Comment by Maheshkumar-novice** [comment]
@lifeparticle

**Comment by lifeparticle** [comment]
![Screen Shot 2022-07-23 at 2 07 31 pm](https://user-images.githubusercontent.com/1612112/180589870-47a45dc2-20d8-4a5b-b604-f5ee3bdfa8cf.png)

This page?

**Comment by Maheshkumar-novice** [comment]
https://github.com/lifeparticle/Ruby-Cheatsheet/pull/15

This one.

**Comment by lifeparticle** [comment]
![Screen Shot 2022-07-23 at 2 12 09 pm](https://user-images.githubusercontent.com/1612112/180589993-0a29f346-b983-4b43-beec-404f5d04d60d.png)

**Comment by Maheshkumar-novice** [comment]
Oh this is strange. I'll look into it.

**Comment by Maheshkumar-novice** [comment]
I'm out now. I'll send the screenshot of my side soon.

**Comment by Maheshkumar-novice** [comment]
@lifeparticle Sorry. I made a mistake. I forgot to `Submit the review` :smiling_face_with_tear:

**Comment by Maheshkumar-novice** [comment]
Can you check now?

**Comment by lifeparticle** [comment]
No problem, I've made some changes according to your comments. Let me know if it looks good, then we can merge it.

**Comment by Maheshkumar-novice** [comment]
@lifeparticle Thanks. Looks good to me.

**Comment by lifeparticle** [comment]
Thanks @Maheshkumar-novice

**Comment by Maheshkumar-novice** [comment]
> Thanks @Maheshkumar-novice

You're welcome @lifeparticle ....Thank you so much for the guidance and help!

**Comment by lifeparticle** [comment]
No problem, you did all the hard work 🙏. Thanks for your time.

**Comment by Maheshkumar-novice** [comment]
:pray:
